-- ============================================================
-- 오늘 모 먹지? 로그인 회원 테이블 (PostgreSQL 16)
-- ============================================================
-- 카카오 로그인 사용자와 개발용 로그인 사용자를 같은 회원으로 관리합니다.
-- JWT 액세스 토큰은 서버 DB에 저장하지 않는 무상태 인증 방식이므로
-- 별도의 로그인 세션 테이블은 생성하지 않습니다.

CREATE TABLE IF NOT EXISTS member (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kakao_id          VARCHAR(50)  NOT NULL,
    nickname          VARCHAR(50)  NOT NULL,
    profile_image_url VARCHAR(500),
    role              VARCHAR(20)  NOT NULL DEFAULT 'USER',
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_member_kakao_id UNIQUE (kakao_id),
    CONSTRAINT ck_member_role CHECK (role IN ('USER', 'ADMIN'))
);

-- 카카오 로그인은 kakao_id로 기존 회원을 조회하므로 UNIQUE 인덱스를 사용합니다.
-- uk_member_kakao_id 제약조건 생성 시 PostgreSQL이 해당 인덱스를 자동 생성합니다.

COMMENT ON TABLE member IS '카카오 로그인 회원';
COMMENT ON COLUMN member.kakao_id IS '카카오에서 제공하는 고유 사용자 ID';
COMMENT ON COLUMN member.profile_image_url IS '카카오 프로필 이미지 URL';
COMMENT ON COLUMN member.role IS '회원 권한: USER 또는 ADMIN';
